select 'Inserciones necesarias para realizar las pruebas' from dual;
INSERT INTO PROVEEDOR (NOMBRE, TIPO_DOCUMENTO, NUM_DOCUMENTO) VALUES ('Joaquin Sabina','CE',1111611111);
INSERT INTO MENAJE (NOMBRE) VALUES ('Sofá');
INSERT INTO TIEMPO_OCUPACION (FECHA_LLEGADA,FECHA_SALIDA,ID) VALUES ('05/05/2020','06/05/2020',1);
INSERT INTO CLIENTE (NOMBRE,TIPO_PERSONA,TIPO_DOCUMENTO,NUM_DOCUMENTO) VALUES ('Pablo Castilla', 'estudiante', 'TI',1111111111);
INSERT INTO SERVICIO (NOMBRE, DESCRIPCION) VALUES ('Internet','Servicio de internet en el inmueble');

select '-----------------------------------------PRUEBAS DE FK TABLA ALOJAMIENTO-----------------------------------------'from dual;
INSERT INTO ALOJAMIENTO (ID, DIRECCION, PROVEEDOR_TIPO_DOC, PROVEEDOR_NUM_DOC) VALUES (2, 'cll 132c #44-44','CE',1111611111);
INSERT INTO ALOJAMIENTO (ID, DIRECCION, PROVEEDOR_TIPO_DOC, PROVEEDOR_NUM_DOC) VALUES (3, 'cll 132c #44-44','CE',2111611111);

select '------------------------------------------PRUEBAS DE FK TABLA EMPRESA-------------------------------------------' from dual;
INSERT INTO EMPRESA (ID_ALOJAMIENTO, NOMBRE) VALUES (2,'Torres de la Floresta');
INSERT INTO EMPRESA (ID_ALOJAMIENTO, NOMBRE) VALUES (20,'Torres de la Floresta');

select '-----------------------------------------PRUEBAS DE FK TABLA HABITACION-----------------------------------------' from dual;
INSERT INTO HABITACION (ID,EMPRESA, NUM_HABITACION, TIPO, UBICACION, CAPACIDAD, COMPARTIDA, TAMANIO) VALUES (1,2,101,'ESTANDAR', 'Primer piso con vista a la calle',2,0,12);
INSERT INTO HABITACION (ID,EMPRESA, NUM_HABITACION, TIPO, UBICACION, CAPACIDAD, COMPARTIDA, TAMANIO) VALUES (10,21,101,'ESTANDAR', 'Primer piso con vista a la calle',2,0,12);

select '-----------------------------------PRUEBAS DE FK TABLA VIVIENDA_UNIVERSITARIA-----------------------------------' from dual;
INSERT INTO VIVIENDA_UNIVERSITARIA (ID_EMPRESA) VALUES (2);
INSERT INTO VIVIENDA_UNIVERSITARIA (ID_EMPRESA) VALUES (11);

select '-------------------------------------------PRUEBAS DE FK TABLA HOTEL--------------------------------------------' from dual;
INSERT INTO HOTEL (ID_EMPRESA, ID_SUPERINTENDENCIA, ID_CAMARA) VALUES (2, 'G12HT24', 'EQ42H42');
INSERT INTO HOTEL (ID_EMPRESA, ID_SUPERINTENDENCIA, ID_CAMARA) VALUES (61, 'G12HT24', 'EQ42H42');

select '-------------------------------------------PRUEBAS DE FK TABLA HOSTAL-------------------------------------------' from dual;
INSERT INTO HOSTAL (ID_EMPRESA,HORARIO_ATENCION,ID_SUPERINTENDENCIA,ID_CAMARA) VALUES (2,'8:00-22:00','39FKIO3','TGW34R2Q4');
INSERT INTO HOSTAL (ID_EMPRESA,HORARIO_ATENCION,ID_SUPERINTENDENCIA,ID_CAMARA) VALUES (81,'8:00-22:00','39FKIO3','TGW34R2Q4');

select '--------------------------------------PRUEBAS DE FK TABLA INMUEBLE_PERSONA--------------------------------------' from dual;
INSERT INTO INMUEBLE_PERSONA (TIPO_PROPIETARIO, NUM_HABITACIONES, AMOBLADO, TIPO_INMUEBLE, ID_ALOJAMIENTO) VALUES ('PROFESOR',3,1,'VIVIENDA_ESPORADICA',2);
INSERT INTO INMUEBLE_PERSONA (TIPO_PROPIETARIO, NUM_HABITACIONES, AMOBLADO, TIPO_INMUEBLE, ID_ALOJAMIENTO) VALUES ('PROFESOR',3,1,'VIVIENDA_ESPORADICA',6);

select '--------------------------------------PRUEBAS DE FK TABLA MENAJE_INMUEBLE---------------------------------------' from dual;
INSERT INTO MENAJE_INMUEBLE (ID_INMUEBLE, NOMBRE_MENAJE, CANTIDAD) VALUES (2,'Sofá',3);
INSERT INTO MENAJE_INMUEBLE (ID_INMUEBLE, NOMBRE_MENAJE, CANTIDAD) VALUES (51,'Sofá',3);
INSERT INTO MENAJE_INMUEBLE (ID_INMUEBLE, NOMBRE_MENAJE, CANTIDAD) VALUES (2,'Escritorio',3);

select '--------------------------------------PRUEBAS DE FK TABLA MENAJE_VIVIENDAU--------------------------------------' from dual;
INSERT INTO MENAJE_VIVIENDAU (ID_VIVIENDAU, NOMBRE_MENAJE, CANTIDAD) VALUES (2,'Sofá',20);
INSERT INTO MENAJE_VIVIENDAU (ID_VIVIENDAU, NOMBRE_MENAJE, CANTIDAD) VALUES (14,'Sofá',20);
INSERT INTO MENAJE_VIVIENDAU (ID_VIVIENDAU, NOMBRE_MENAJE, CANTIDAD) VALUES (2,'Escritorio',20);

select '------------------------------------PRUEBAS DE FK TABLA ALOJAMIENTO_SERVICIO------------------------------------' from dual;
INSERT INTO ALOJAMIENTO_SERVICIO(NOMBRE_SERVICIO,ID_ALOJAMIENTO,COSTO) VALUES ('Internet',2,70000);
INSERT INTO ALOJAMIENTO_SERVICIO(NOMBRE_SERVICIO,ID_ALOJAMIENTO,COSTO) VALUES ('Internet',19,70000);
INSERT INTO ALOJAMIENTO_SERVICIO(NOMBRE_SERVICIO,ID_ALOJAMIENTO,COSTO) VALUES ('TV Cable',2,70000);

select '------------------------------------PRUEBAS DE FK TABLA HABITACION_SERVICIO-------------------------------------' from dual;
INSERT INTO HABITACION_SERVICIO (NOMBRE_SERVICIO, ID_HABITACION, COSTO) VALUES ('Internet',1,0);
INSERT INTO HABITACION_SERVICIO (NOMBRE_SERVICIO, ID_HABITACION, COSTO) VALUES ('Internet',10,0);
INSERT INTO HABITACION_SERVICIO (NOMBRE_SERVICIO, ID_HABITACION, COSTO) VALUES ('TV Cable',1,0);

select '------------------------------------------PRUEBAS DE FK TABLA RESERVA-------------------------------------------' from dual;
INSERT INTO RESERVA (ESTADO,FECHA,ID,CLIENTE_NUM_DOC,CLIENTE_TIPO_DOC,ALOJAMIENTO,ID_TIEMPO,PRECIO) VALUES ('A',CURRENT_DATE,1,1111111111,'TI',2,1,1);
INSERT INTO RESERVA (ESTADO,FECHA,ID,CLIENTE_NUM_DOC,CLIENTE_TIPO_DOC,ALOJAMIENTO,ID_TIEMPO,PRECIO) VALUES ('A',CURRENT_DATE,2,2111111111,'TI',2,1,1);
INSERT INTO RESERVA (ESTADO,FECHA,ID,CLIENTE_NUM_DOC,CLIENTE_TIPO_DOC,ALOJAMIENTO,ID_TIEMPO,PRECIO) VALUES ('A',CURRENT_DATE,3,1111111111,'TI',69,1,1);
INSERT INTO RESERVA (ESTADO,FECHA,ID,CLIENTE_NUM_DOC,CLIENTE_TIPO_DOC,ALOJAMIENTO,ID_TIEMPO,PRECIO) VALUES ('A',CURRENT_DATE,4,1111111111,'TI',2,2,1);

select '-------------------------------------PRUEBAS DE FK TABLA RESERVA_HABITACION-------------------------------------' from dual;
INSERT INTO RESERVA_HABITACION (ID_RESERVA,ID_HABITACION) VALUES (1,1);
INSERT INTO RESERVA_HABITACION (ID_RESERVA,ID_HABITACION) VALUES (2,1);
INSERT INTO RESERVA_HABITACION (ID_RESERVA,ID_HABITACION) VALUES (1,12);

select '----------------------------------PRUEBAS DE FK TABLA INMUEBLE_TIEMPO_OCUPADA-----------------------------------' from dual;
INSERT INTO INMUEBLE_TIEMPO_OCUPADA (ID_INMUEBLE,ID_TIEMPO) VALUES (2,1);
INSERT INTO INMUEBLE_TIEMPO_OCUPADA (ID_INMUEBLE,ID_TIEMPO) VALUES (2,88);
INSERT INTO INMUEBLE_TIEMPO_OCUPADA (ID_INMUEBLE,ID_TIEMPO) VALUES (54,1);

select '---------------------------------PRUEBAS DE FK TABLA HABITACION_TIEMPO_OCUPADA----------------------------------' from dual;
INSERT INTO HABITACION_TIEMPO_OCUPADA (ID_HABITACION,ID_TIEMPO_OCUPACION) VALUES (1,1);
INSERT INTO HABITACION_TIEMPO_OCUPADA (ID_HABITACION,ID_TIEMPO_OCUPACION) VALUES (7,1);
INSERT INTO HABITACION_TIEMPO_OCUPADA (ID_HABITACION,ID_TIEMPO_OCUPACION) VALUES (1,3);
